// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SearchClient is an autogenerated mock type for the SearchClient type
type SearchClient struct {
	mock.Mock
}

// Show provides a mock function with given fields: input, verbose
func (_m *SearchClient) Show(input string, verbose bool) error {
	ret := _m.Called(input, verbose)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = rf(input, verbose)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSearchClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewSearchClient creates a new instance of SearchClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSearchClient(t mockConstructorTestingTNewSearchClient) *SearchClient {
	mock := &SearchClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
